server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default
  application:
    name: catalogue

--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: catalogue

app:
  environment:
    catalogue-host: none