server:
  port: 8081

spring:
  config:
    activate:
      on-profile: default
  application:
    name: clothings
  datasource:
    url: jdbc:mysql://${clothings_db:localhost}:3306/clothings_db
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: update

app:
  environment:
    clothings-host: ${clothings-host:localhost}

--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: clothings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: 123123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  environment:
    clothings-host: none