server:
  port: 8082

spring:
  config:
    activate:
      on-profile: default
  application:
    name: customisations
  datasource:
    url: jdbc:mysql://${customisations_db:localhost}:3306/customisations_db
    username: root
    password: 123123
  jpa:
    hibernate:
      ddl-auto: create

app:
  environment:
    customisations-host: ${customisations-host:localhost}

--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: customisations
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password: 123123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  environment:
    customisations-host: none